### ISSUE TITLE
Quick Sort

### ISSUE THREAD

**Issue by dsnehasish74** [dsnehasish74/Hacktoberfest21_Algo_Collection#2]

**Comment by dsnehasish74** [comment]
C Code is submitted try with other languages

**Comment by uzzal623** [comment]
I  want to do it in python.

**Comment by dsnehasish74** [comment]
@uzzal623 yes you can submit your pull request

**Comment by rsh-raj** [comment]
I want to do it in C++

**Comment by Sans0709** [comment]
I wish to do it in java

**Comment by dsnehasish74** [comment]
@Sans0709 Submit Your pull

**Comment by Pratixingh** [comment]
I want to do this code in Cpp could u please assign me.

**Comment by Pratixingh** [comment]
Created a pull request of solved quick sort problem please check.

**Comment by Gangorra** [comment]
Hi, I'm new to this world, I'm trying to participate in the hacktoberfest event. I don't know if this is the right place to ask you about it, but can I add any files in any language?

**Comment by dsnehasish74** [comment]
@Gangorra  yes you can , choose any algorithm which is not present and submit a pull request following that contribution guideline.
