### ISSUE TITLE
String Matching Algorithm

### ISSUE THREAD

**Issue by sarthakdelori** [dsnehasish74/Hacktoberfest21_Algo_Collection#25]
I will implement the algorithm for how to find if a pattern string exist in a text string or not. I will do it in C++.

**Comment by ayushjindal23** [comment]
Can I work on this ?

**Comment by Viditjain04** [comment]
I have made a pull request #57 on z algorithm, which is used for string matching , please accept it and merge it .

**Comment by us25999** [comment]
I can solce this problem
