### ISSUE TITLE
Structure this Repo

### ISSUE THREAD

**Issue by dsnehasish74** [dsnehasish74/Hacktoberfest21_Algo_Collection#27]
To structure, this repo does create separate folders for C++, C, JAVA, PYTHON and separate language-specific files into them. If any query is needed do comment, I will solve your doubts regarding this issue.

**Comment by yashjawale** [comment]
Hello, can I work on this issue?
As far as I understand, I need to create separate folders for the file types and move those files into them, right?

**Comment by dsnehasish74** [comment]
@yashjawale The issue is already resolved. Please find any other issue to work

**Comment by yashjawale** [comment]
@dsnehasish74 No problem, Thanks : )
