### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by dsnehasish74** [dsnehasish74/Hacktoberfest21_Algo_Collection#36]
Improve the readme Design and Give the link of each problem in the readme under each language section

**Comment by yashjawale** [comment]
Hello @dsnehasish74 , can I work on this issue?

**Comment by dsnehasish74** [comment]
@yashjawale yes you can work

**Comment by yashjawale** [comment]
Thanks

**Comment by yashjawale** [comment]
@dsnehasish74, I've observed that the algorithm files use different naming conventions. Can we specify a naming convention for the files like lowercase separated with hyphens?

**Comment by dsnehasish74** [comment]
@yashjawale yah that's a great idea. If you can do that it will be great

**Comment by yashjawale** [comment]
Ok

**Comment by Viditjain04** [comment]
I have updated the readme file and made PR #60, please review and accept and merge it.

**Comment by yashjawale** [comment]
@dsnehasish74 Please let me know if there are any changes that need to be made

**Comment by yashjawale** [comment]
Sorry if there are any mistakes, I'm new to repository contributions
