### ISSUE TITLE
All Sorting Algorithms

### ISSUE THREAD

**Issue by dsnehasish74** [dsnehasish74/Hacktoberfest21_Algo_Collection#6]

**Comment by Sans0709** [comment]
i will like to work on this issue .

**Comment by dsnehasish74** [comment]
@Sans0709 yes Submit Your Pull

**Comment by raazanand** [comment]
heyy @dsnehasish74 ! I am surely interested in this problem, Please assign it to me.

**Comment by dsnehasish74** [comment]
@raazanand  yes please submit your pull

**Comment by Prateek-kannojia** [comment]
hi @dsnehasish74 Can you please assign me this issue with the label of hacktoberfest.. I will like to work on this.

**Comment by raazanand** [comment]
> @raazanand yes please submit your pull

Please review my PR #21

**Comment by AkshatBhat** [comment]
I have added the Merge Sort algorithm in Java #23 as nobody has done it in this repo in Java yet. Please merge it. Thank you.

**Comment by dsnehasish74** [comment]
@Prateek-kannojia  you can submit your pull request

**Comment by Mayankjha997** [comment]
Hello @dsnehasish74 ;
I want to add merge sort  in Python  please assign this issue to me.

**Comment by NidhiNivedita6** [comment]
Can I add Count Sort in C language?

**Comment by dsnehasish74** [comment]
@Mayankjha997 and @NidhiNivedita6  you can submit your Pull request

**Comment by us25999** [comment]
I want to work on this, can I?

**Comment by NisargChokshi** [comment]
@dsnehasish74 Can I add Implementation of Sorting Algorithms using JavaScript?

**Comment by dsnehasish74** [comment]
@NisargChokshi Yes you can submit your pr

**Comment by Anvesh0110** [comment]
@dsnehasish74 Can I add Insertion Sort using C++?
